apiVersion: apps/v1 
kind: Deployment
metadata:
  name: time-stamp4
  labels: 
     app: time-stamp4

spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-stamp4

  template:
    metadata:
      labels:
        app: time-stamp4
    spec:
      containers:
      - name: rohit-container
        image: rohit5521/mvnprojectweb
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
